# Generated by Django 5.1.1 on 2024-10-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT 1",
            reverse_sql="SELECT 1",
        ),
    ]
