# Generated by Django 5.1.1 on 2024-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0002_auto_20241008_0415"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="edad",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="estado",
            field=models.CharField(
                choices=[
                    ("SANO", "Sano"),
                    ("ENFERMO", "Enfermo"),
                    ("EN_TRATAMIENTO", "En tratamiento"),
                    ("CUARENTENA", "En cuarentena"),
                ],
                default="SANO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="peso_actual",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("M", "Macho"), ("H", "Hembra")],
                max_length=1,
                null=True,
            ),
        ),
    ]
